# Generated by Django 2.2.16 on 2022-05-31 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='category',
            new_name='categories',
        ),
    ]
