# Generated by Django 2.2.16 on 2022-06-05 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_comment_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='title_name',
            new_name='name',
        ),
    ]
