# Generated by Django 2.2.16 on 2022-05-31 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220531_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='categories',
            new_name='category',
        ),
    ]
